### ISSUE TITLE
VHS Tech Website pics

### ISSUE THREAD

**Issue by VHSTech** [VHSTech/vhstech.github.io#1]
![logo_1799624_web](https://cloud.githubusercontent.com/assets/14814697/10065260/e6577f62-6237-11e5-8b2e-952afe40dd08.jpg)

**Comment by VHSTech** [comment]
![vhs tech](https://cloud.githubusercontent.com/assets/14814697/10065278/3c8cfd58-6238-11e5-9cf7-e89111c56640.png)

**Comment by VHSTech** [comment]
![null 1](https://cloud.githubusercontent.com/assets/14814697/10065283/55785c22-6238-11e5-8765-ccbfde510f47.png)

**Comment by VHSTech** [comment]
![preview_32x32](https://cloud.githubusercontent.com/assets/14814697/10093076/91af73b8-6302-11e5-8456-e6ce35f38dc2.jpg)

**Comment by VHSTech** [comment]
![preview_32x32_converted](https://cloud.githubusercontent.com/assets/14814697/10093131/0e2b114a-6303-11e5-9c93-07c2785c1861.png)

**Comment by Copetan** [comment]
what are these mutinous comments

**Comment by Copetan** [comment]
This is fixed, favicon added
